-- SYSTEM ADMIN ROLE (Full DBA privileges)
CREATE ROLE SYS_ADMIN;
GRANT CONNECT, RESOURCE, DBA TO SYS_ADMIN;

CREATE USER sys_admin IDENTIFIED BY Sys@1234;
GRANT SYS_ADMIN TO sys_admin;

-- FINANCE ADMIN ROLE (Limited finance management)
CREATE ROLE FIN_ADMIN;
GRANT CONNECT, RESOURCE TO FIN_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON Transaction_Info TO FIN_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON Budget TO FIN_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON Saving_Goal TO FIN_ADMIN;

CREATE USER finance_admin IDENTIFIED BY Fin@1234;
GRANT FIN_ADMIN TO finance_admin;

-- AUDIT ADMIN ROLE (Read-only)
CREATE ROLE AUDIT_ADMIN;
GRANT CONNECT TO AUDIT_ADMIN;
GRANT SELECT ON User_Audit_Log TO AUDIT_ADMIN;
GRANT SELECT ON UserInfo TO AUDIT_ADMIN;
GRANT SELECT ON Transaction_Info TO AUDIT_ADMIN;

CREATE USER audit_admin IDENTIFIED BY Aud@1234;
GRANT AUDIT_ADMIN TO audit_admin;

-- Expire passwords after 90 days
ALTER PROFILE DEFAULT LIMIT PASSWORD_LIFE_TIME 90;

-- Prevent reuse of old passwords
ALTER PROFILE DEFAULT LIMIT PASSWORD_REUSE_MAX 5;

-- Lock account after 5 failed login attempts
ALTER PROFILE DEFAULT LIMIT FAILED_LOGIN_ATTEMPTS 5;