-- USERINFO table
CREATE TABLE UserInfo (
    user_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    firstName VARCHAR2(50) NOT NULL,
    lastName VARCHAR2(50)NOT NULL,
    email VARCHAR2(100) UNIQUE NOT NULL,
    password VARCHAR2(255) NOT NULL,
    occupation VARCHAR2(50)NOT NULL,
    houseNO VARCHAR2(50)NOT NULL,
    streetName VARCHAR2(100)NOT NULL,
    city VARCHAR2(50)NOT NULL,
    phone VARCHAR2(20) NOT NULL,
    isDeleted CHAR(1) DEFAULT 'N' CHECK(isDeleted IN ('Y','N'))
);

SELECT * FROM userinfo;

CREATE TABLE Note (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,  
    note_id NUMBER NOT NULL,                                 
    user_id NUMBER NOT NULL,
    title VARCHAR2(100) NOT NULL,
    description VARCHAR2(255) NOT NULL,
    actionDate DATE,
    updatedAt TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT note_unique UNIQUE (note_id, user_id),          
    FOREIGN KEY (user_id) REFERENCES UserInfo(user_id)
);

-- ACCOUNT_TYPE table
CREATE TABLE Account_Type (
    acc_type_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    accTypeName VARCHAR2(50) NOT NULL,
    assetOrLiability VARCHAR2(50) CHECK(assetOrLiability IN ('Asset','Liability'))
);

--ASSET TYPES
INSERT INTO Account_Type (accTypeName, assetOrLiability) VALUES ('Savings Account', 'Asset');
--LIABILITY TYPES
INSERT INTO Account_Type (accTypeName, assetOrLiability) VALUES ('Credit Card', 'Liability');

SELECT * FROM account_type;

CREATE TABLE Account (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,  
    account_id NUMBER NOT NULL,                              
    user_id NUMBER NOT NULL,
    acc_type_id NUMBER NOT NULL,
    nickname VARCHAR2(50),
    reference VARCHAR2(50),
    institution VARCHAR2(50),
    balance NUMBER(12,2) DEFAULT 0,
    isActive CHAR(1) DEFAULT 'Y' CHECK (isActive IN ('Y', 'N')),
    CONSTRAINT acc_unique UNIQUE (account_id, user_id),       
    FOREIGN KEY (user_id) REFERENCES UserInfo(user_id),
    FOREIGN KEY (acc_type_id) REFERENCES Account_Type(acc_type_id)
);

SELECT * FROM ACCOUNT;

CREATE TABLE Transaction_Category (
    category_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    categoryName VARCHAR2(100) NOT NULL
);

-- Income Category
INSERT INTO Transaction_Category (categoryName) VALUES ('Income');

-- Expense Categories
INSERT INTO Transaction_Category (categoryName) VALUES ('Food & Groceries');
INSERT INTO Transaction_Category (categoryName) VALUES ('Transportation');
INSERT INTO Transaction_Category (categoryName) VALUES ('Utilities');
INSERT INTO Transaction_Category (categoryName) VALUES ('Rent');
INSERT INTO Transaction_Category (categoryName) VALUES ('Healthcare');
INSERT INTO Transaction_Category (categoryName) VALUES ('Insurance');
INSERT INTO Transaction_Category (categoryName) VALUES ('Education');
INSERT INTO Transaction_Category (categoryName) VALUES ('Shopping');
INSERT INTO Transaction_Category (categoryName) VALUES ('Entertainment');
INSERT INTO Transaction_Category (categoryName) VALUES ('Travel');
INSERT INTO Transaction_Category (categoryName) VALUES ('Taxes');
INSERT INTO Transaction_Category (categoryName) VALUES ('Other Expenses');

select * from transaction_category;

-- TRANSACTION_info table
CREATE TABLE Transaction_Info (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,  
    transaction_id NUMBER NOT NULL,                          
    user_id NUMBER NOT NULL,
    account_id NUMBER NOT NULL,
    category_id NUMBER,
    amount NUMBER(12,2) NOT NULL,
    transactionType VARCHAR2(20) CHECK (transactionType IN ('Income', 'Expense')),
    description VARCHAR2(255),
    tranDate DATE DEFAULT SYSDATE,
    tranTime TIMESTAMP DEFAULT SYSTIMESTAMP,
    isDeleted CHAR(1) DEFAULT 'N' CHECK (isDeleted IN ('Y','N')),
    CONSTRAINT trans_unique UNIQUE (transaction_id, user_id), 
    FOREIGN KEY (account_id, user_id) REFERENCES Account(account_id, user_id),
    FOREIGN KEY (category_id) REFERENCES Transaction_Category(category_id)
);

select * from transaction_info;


CREATE TABLE Budget (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,  
    budget_id NUMBER NOT NULL,                               
    user_id NUMBER NOT NULL,
    category_id NUMBER NOT NULL,
    startDate DATE NOT NULL,
    endDate DATE NOT NULL,
    warningLimit NUMBER(12,2) NOT NULL,
    maximumLimit NUMBER(12,2) NOT NULL,
    description VARCHAR2(255),
    CONSTRAINT budget_unique UNIQUE (budget_id, user_id),
    FOREIGN KEY (user_id) REFERENCES UserInfo(user_id),
    FOREIGN KEY (category_id) REFERENCES Transaction_Category(category_id)
);

select * from budget;


CREATE TABLE Saving_Goal (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,  
    goal_id NUMBER NOT NULL,                                  
    user_id NUMBER NOT NULL,
    account_id NUMBER NOT NULL,
    goalName VARCHAR2(100) NOT NULL,
    targetAmount NUMBER(12,2),
    currentAmount NUMBER(12,2) DEFAULT 0,
    startDate DATE NOT NULL,
    endDate DATE NOT NULL,
    isActive CHAR(1) DEFAULT 'Y' CHECK(isActive IN ('Y','N')),
    CONSTRAINT goal_unique UNIQUE (goal_id, user_id),          
    FOREIGN KEY (user_id) REFERENCES UserInfo(user_id),
    FOREIGN KEY (account_id, user_id) REFERENCES Account(account_id, user_id)
);

CREATE TABLE Saving_Transaction (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,   
    sav_tran_id NUMBER NOT NULL,                    
    user_id NUMBER NOT NULL,
    goal_id NUMBER NOT NULL,
    account_id NUMBER NOT NULL,
    amount NUMBER(12,2),
    description VARCHAR2(255),
    tranDate DATE DEFAULT SYSDATE,
    tranTime TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT saving_trans_unique UNIQUE (saving_transaction_id, user_id),
    FOREIGN KEY (user_id) REFERENCES UserInfo(user_id),
    FOREIGN KEY (goal_id, user_id) REFERENCES Saving_Goal(goal_id, user_id),
    FOREIGN KEY (account_id, user_id) REFERENCES Account(account_id, user_id)
);

alter table Saving_Transaction rename column saving_transaction_id to sav_tran_id;

