-- ADMININFO table
CREATE TABLE AdminInfo (
    admin_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    firstName VARCHAR2(50) NOT NULL,
    lastName VARCHAR2(50) NOT NULL,
    officeEmail VARCHAR2(100) UNIQUE NOT NULL,
    password VARCHAR2(100) NOT NULL,
    role VARCHAR2(50) NOT NULL,         
    department VARCHAR2(50) NOT NULL,   
    officePhone VARCHAR2(20) NOT NULL
);

-- USERINFO table
CREATE TABLE UserInfo (
    user_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    firstName VARCHAR2(50) NOT NULL,
    lastName VARCHAR2(50)NOT NULL,
    email VARCHAR2(100) UNIQUE NOT NULL,
    password VARCHAR2(255) NOT NULL,
    occupation VARCHAR2(50)NOT NULL,
    houseNO VARCHAR2(50)NOT NULL,
    streetName VARCHAR2(100)NOT NULL,
    city VARCHAR2(50)NOT NULL,
    phone VARCHAR2(20) NOT NULL,
    isDeleted CHAR(1) DEFAULT 'N' CHECK(isDeleted IN ('Y','N'))
);

--NOTE table
CREATE TABLE Note (
    note_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER NOT NULL,
    title VARCHAR2(100) NOT NULL,
    description VARCHAR2(255) NOT NULL,
    actionDate DATE,
    updatedAt TIMESTAMP DEFAULT SYSTIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES UserInfo(user_id)
);

-- ACCOUNT_TYPE table
CREATE TABLE Account_Type (
    acc_type_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    accTypeName VARCHAR2(50) NOT NULL,
    assetOrLiability VARCHAR2(50) CHECK(assetOrLiability IN ('Asset','Liability'))
);

-- ACCOUNT table
CREATE TABLE Account (
    account_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER NOT NULL,
    acc_type_id NUMBER NOT NULL,
    nickname VARCHAR2(50),
    reference VARCHAR2(50),
    instituion VARCHAR2(50),
    balance NUMBER(12,2) DEFAULT 0,
    isActive CHAR(1) DEFAULT 'Y' CHECK (isActive IN ('Y', 'N')),
    FOREIGN KEY (acc_type_id) REFERENCES Account_Type(acc_type_id),
    FOREIGN KEY (user_id) REFERENCES UserInfo(user_id)
);

-- TRANSACTION_CATEGORY table
CREATE TABLE Transaction_Category (
    category_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    categoryName VARCHAR2(100) NOT NULL
);

-- TRANSACTION table
CREATE TABLE Transaction_Info (
    transaction_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER NOT NULL,
    account_id NUMBER NOT NULL,
    category_id NUMBER,
    amount NUMBER(12,2) NOT NULL,
    transactionType VARCHAR2(20) CHECK (transactionType IN ('Income', 'Expense')),
    description VARCHAR2(255),
    tranDate DATE DEFAULT SYSDATE,
    tranTime TIMESTAMP DEFAULT SYSTIMESTAMP,
    isDeleted CHAR(1) DEFAULT 'N' CHECK(isDeleted IN ('Y','N')),
    FOREIGN KEY (user_id) REFERENCES UserInfo(user_id),
    FOREIGN KEY (account_id) REFERENCES Account(account_id),
    FOREIGN KEY (category_id) REFERENCES Transaction_Category(category_id)
);

-- BUDGET table
CREATE TABLE Budget (
    budget_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER NOT NULL,
    category_id NUMBER NOT NULL,
    startDate DATE NOT NULL,
    endDate DATE NOT NULL,
    warningLimit NUMBER(12,2) NOT NULL,
    maximumLimit NUMBER(12,2)NOT NULL,
    description VARCHAR2(255),
    FOREIGN KEY (user_id) REFERENCES UserInfo(user_id),
    FOREIGN KEY (category_id) REFERENCES Transaction_Category(category_id)
);
-- INTERNAL_TRANSACTIONS table
CREATE TABLE Internal_Transaction (
    int_tran_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER NOT NULL,
    from_account_id NUMBER NOT NULL,
    to_account_id NUMBER NOT NULL,
    amount NUMBER(12,2) NOT NULL,
    transferType VARCHAR2(50)NOT NULL,
    description VARCHAR2(255),
    tranDate DATE DEFAULT SYSDATE,
    tranTime TIMESTAMP DEFAULT SYSTIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES UserInfo(user_id),
    FOREIGN KEY (from_account_id) REFERENCES Account(account_id),
    FOREIGN KEY (to_account_id) REFERENCES Account(account_id)
);

-- SAVING_GOAL table
CREATE TABLE Saving_Goal (
    goal_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER NOT NULL,
    account_id NUMBER NOT NULL,
    goalName VARCHAR2(100)NOT NULL,
    targetAmount NUMBER(12,2),
    currentAmount NUMBER(12,2) DEFAULT 0,
    startDate DATE NOT NULL,
    endDate DATE NOT NULL,
    isActive CHAR(1) DEFAULT 'Y' CHECK(isActive IN ('Y','N')),
    FOREIGN KEY (user_id) REFERENCES UserInfo(user_id),
    FOREIGN KEY (account_id) REFERENCES Account(account_id)
);

-- SAVING_TRANSACTION table
CREATE TABLE Saving_Transaction (
    saving_transaction_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER NOT NULL,
    goal_id NUMBER NOT NULL,
    account_id NUMBER NOT NULL,
    amount NUMBER(12,2),
    description VARCHAR2(255),
    tranDate DATE DEFAULT SYSDATE,
    tranTime TIMESTAMP DEFAULT SYSTIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES UserInfo(user_id),
    FOREIGN KEY (goal_id) REFERENCES Saving_Goal(goal_id),
    FOREIGN KEY (account_id) REFERENCES Account(account_id)
);


select * from transaction_info
select * from internal_transaction
select * from saving_transaction

alter table internal_transaction
rename column transDate to trandate














